######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 7 12:09:20 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fifthteens.h
SOURCES += fifthteens.cpp main.cpp
